all: clang-tidy updates

diff --git a/.github/workflows/static-analyzer-clang-analyzer.yml b/.github/workflows/static-analyzer-clang-analyzer.yml
--- a/.github/workflows/static-analyzer-clang-analyzer.yml
+++ b/.github/workflows/static-analyzer-clang-analyzer.yml
@@ -1,12 +1,12 @@
 # Copyright (C) Markus Franz Xaver Johannes Oberhumer
-name: 'Static Analyzer - clang scan-build'
+name: 'Static Analyzer - clang-analyzer'
 
 on:
   schedule: [cron: '20 5 * * 3'] # run weekly Wednesday 05:20 UTC
   workflow_dispatch:
 
 jobs:
-  job-analyze-clang: # uses cmake + make
+  job-analyze-clang-analyzer: # uses cmake + make
     strategy:
       fail-fast: false
       matrix: {container: ['alpine:3.16','alpine:3.17','alpine:3.18','alpine:edge','i386/alpine:edge']}
@@ -15,7 +15,7 @@ jobs:
     container: ${{ matrix.container }}
     steps:
       - name: ${{ format('Install packages {0}', matrix.container) }}
-        run: 'apk update && apk upgrade && apk add bash clang clang-analyzer cmake g++ git make'
+        run: 'apk update && apk upgrade && apk add clang clang-analyzer cmake g++ git make'
       - name: ${{ format('Check out UPX {0} source code', github.ref_name) }}
         run: |
           git clone --branch "$GITHUB_REF_NAME" --depth 1 https://github.com/upx/upx
@@ -23,4 +23,5 @@ jobs:
       - name: 'Perform clang scan-build Analysis Debug'
         run: 'make -C upx build/extra/scan-build/debug'
       - name: 'Perform clang scan-build Analysis Release'
+        if: success() || failure() # run this step even if the previous step failed
         run: 'make -C upx build/extra/scan-build/release'
